version: '3.8'

services:
  # The Backend API Service
  backend:
    # Use the image from your Docker Hub
    image: ${{ secrets.DOCKERHUB_USERNAME }}/trip-planner-backend:latest
    # The command to start your API
    command: uvicorn api_app:app --host 0.0.0.0 --port 8000
  
  # The Frontend Streamlit Service
  frontend:
    # Use the image from your Docker Hub
    image: ${{ secrets.DOCKERHUB_USERNAME }}/trip-planner-frontend:latest
    # The command to start Streamlit
    command: streamlit run streamlit_app.py --server.port=8501